Update RUST_ERROR_REGEX to take advantage of source path remapping.
Summary:
Previously, the `RUST_ERROR_REGEX` was designed to strip off the `buck-out`
prefix of the path in an error message from the Rust compiler as a hacky way
to map the path in the diagnostic from `rustc` to the path of the original
source file. This is because diagnostics looked like this:

```
stderr: error: expected one of `::`, `;`, or `as`, found `use`
  --> buck-out/dev/bin/scm/mononoke/eden-server/eden_server#binary-container/scm/mononoke/eden-server/src/main.rs:40:1
```

However, we recently made it possible to use the "unstable" feature of `rustc`
to do path remapping (`-Zremp-path-prefix-{from,to}`):

https://github.com/facebook/buck/commit/ff2168b9a1d83c21e3a7aa3fbc6ebb397e1cea44

so now diagnostics look like this, referencing the path of the original source file:

```
error: expected `;`, found `use`
  --> scm/mononoke/eden_server/src/main.rs:41:1
```

Reviewed By: jsgf

Differential Revision: D6117717

fbshipit-source-id: c9aa6baab3bc59559279354567105d580665ee61