Fix undefined reference to lldb
Summary: D4101266 broke this

Reviewed By: yinghuitan

Differential Revision: D4143145

fbshipit-source-id: 6d34e66a387457ec3b83159052d5ac4f679764a0