Debugger: resolve node to process.execPath
Summary:
In Nuclide environment, that'd be the RPC `node` version when `useLocalRpc` is `true`.

When `useLocalRpc` is `false` or in Atom IDE environment (no rpc), that'll use `Atom Helper` instead of the system's `node` version (hence, binary bundles - e.g. `nuclide-prebuilt-libs` would work just fine)

That should fix the issue with Atom IDE's `atom-ide-debugger-native-gdb` failing with a different system node version error:
```
Error: Cannot find module '/Users/max/.atom/packages/atom-ide-debugger-native-gdb/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.4-node-v59-darwin-x64/pty.node'
```

Reviewed By: ebluestein

Differential Revision: D7680885

fbshipit-source-id: 9e6d032b5bf8465c2928d4c08f7da629f5486ef7