update to eslint-plugin-prettify@2.0.2
Summary:
We've now confirmed that the weird "undefined" errors are coming from Prettier (see https://circleci.com/gh/facebook/nuclide/1112). However, there's not enough information in those logs to follow-up on. This `eslint-plugin-prettify` update has extra verbose error logging: https://github.com/zertosh/eslint-plugin-prettify/commit/b65c78225e54af17f5d23f0aad34d5ded7d18773. We should now get errors like this:

```
Error: Prettier exception:
---ERROR---
Error
    at EventEmitter.Program:exit (/Users/asuarez/src/github/eslint-plugin-prettify/rule.js:78:17)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/Users/asuarez/src/github/eslint-plugin-prettify/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/asuarez/src/github/eslint-plugin-prettify/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.leaveNode (/Users/asuarez/src/github/eslint-plugin-prettify/node_modules/eslint/lib/util/node-event-generator.js:317:14)
    at CodePathAnalyzer.leaveNode (/Users/asuarez/src/github/eslint-plugin-prettify/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:622:23)
    at CommentEventGenerator.leaveNode (/Users/asuarez/src/github/eslint-plugin-prettify/node_modules/eslint/lib/util/comment-event-generator.js:111:23)
    at Traverser.leave (/Users/asuarez/src/github/eslint-plugin-prettify/node_modules/eslint/lib/eslint.js:932:36)
    at Traverser.__execute (/Users/asuarez/src/github/eslint-plugin-prettify/node_modules/estraverse/estraverse.js:397:31)
---PRETTIER_OPTIONS---
undefined
---SOURCE---
a();
```

Reviewed By: matthewwithanm

Differential Revision: D5062552

fbshipit-source-id: 76429636175f04d3b9395fa55c6ab182bae8daec