cleared up confusing error message inside nuclide-diff-view
Summary:
When trying to diff any files in my project, I'd get:

```
Cannot open diff view for file: /Users/dallin/code/kualico/cm/server/resources/workflow/types/types.js
Error: git
```

Which made me think nuclide wasn't able to find my git binary. This change makes that error message a little clearer:

```
Cannot open diff view for file: /Users/dallin/code/kualico/cm/server/resources/workflow/types/types.js
Error: Diff view only supports hg repositories right now: git
```
Closes https://github.com/facebook/nuclide/pull/109
Github Author: Dallin Osmun <dosmun@gmail.com>