Handle undefined nuclideConfig in nuclide-jest
Summary:
Creating a package does not autopopulate a blank `nuclide.config = {}` in `package.json`. This means that any new `*-spec.js` will fail due to the following:
```
$ atom --dev --test pkg/fb-ui-component-tools/spec/ui-component-ast-spec.js
 FAIL  pkg/fb-ui-component-tools/spec/ui-component-ast-spec.js
  ui-component-ast
    ✕ retrieves required props from an AST (6ms)

  ● ui-component-ast › retrieves required props from an AST

    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)

      26 |   // and it doesn't load for unit tests, it's necessary to manually
      27 |   // construct any default config that they define.
    > 28 |   Object.keys(nuclideConfig).forEach(key => {
         |          ^
      29 |     global.atom.config.setSchema(
      30 |       `${pkg.name}.${key}`,
      31 |       nuclideConfig[key]

      at Object.<anonymous>.beforeEach (../../modules/nuclide-jest/atomSetup.js:28:10)

Test Suites: 1 failed, 1 total
1 failed, 1 total
Snapshots:   0 total
Time:        0.434s
Ran all test suites matching /\/Users\/emilyhorsman\/fbsource\/xplat\/nuclide\/pkg\/fb-ui-component-tools\/spec\/ui-component-ast-spec.js/i.
```

This commit adds a default empty object.

Reviewed By: wbinnssmith

Differential Revision: D8143269

fbshipit-source-id: 068cd94b5c882f1f4dabd6b8cebd60aa1c77b3f9